### ISSUE TITLE
Stripe CLI setup Fixed Priced Subs with Node + React not working

### ISSUE THREAD

**Issue by ElliottJPerry** [stripe-samples/subscription-use-cases#730]
# Bug report

## Describe the bug

Setting up the Fixed Priced Subs subscription use case Stripe sample using the Stripe CLI with options Node + React is not working. After running the Stripe CLI tool, installing dependencies and running the server, navigating to `/` throws error:

`Error: ENOENT: no such file or directory, stat '../subscription-use-cases/client/register.html'`

This is because of the following endpoint in `server.js`:

```
app.get('/', (req, res) => {
  const path = resolve(process.env.STATIC_DIR + '/register.html');
  res.sendFile(path);
});
```

## To Reproduce

1. Using the Stripe CLI, run `stripe samples create subscription-use-cases`.
2. Select `fixed-priced-subscriptions`.
3. Select `react`.
4. Select `node`.
5. Run `cd subscription-use-cases/server` (as per [README](https://github.com/stripe-samples/subscription-use-cases)).
6. Run `npm install` (as per Node server [README](https://github.com/stripe-samples/subscription-use-cases/tree/main/fixed-price-subscriptions/server/node)).
7. Run `npm start` (as per Node server [README](https://github.com/stripe-samples/subscription-use-cases/tree/main/fixed-price-subscriptions/server/node)).
8. Navigate to `/`.

## Expected behavior

Successful launch of Fixed Priced Subs subscription use case Stripe sample.

## Screenshots

File tree after running Stripe CLI:

<img width="450" alt="file-tree" src="https://user-images.githubusercontent.com/4981637/226706700-8402a9e7-abc0-498e-bd9c-44b34e277702.png">

**Comment by davidgs** [comment]
Not working for me, but with a different error. 

```
% npm start

> fixed-price-subscription@0.2.0 start
> react-scripts start

ℹ ｢wds｣: Project is running at http://192.168.120.226/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/davidgs/github.com/subscription-use-cases/client/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/davidgs/github.com/subscription-use-cases/client/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/davidgs/github.com/subscription-use-cases/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/davidgs/github.com/subscription-use-cases/client/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.5.0
```

Is Node v21.5.0 not supported?

**Comment by hideokamoto-stripe** [comment]
@davidgs 
Thank you for the report. The react sample was created using Create React App. The error reported seems to be due to a library used internally by Create React App:
https://github.com/facebook/create-react-app/issues/11708#issuecomment-986309926

As there seems to be no releases from Create React App from the year 2022, it may be necessary to consider migrating to something like Vite.
 As a temporary workaround, please use NODE_OPTIONS='--openssl-legacy-provider' option like the following:
`NODE_OPTIONS='--openssl-legacy-provider' react-scripts start`

Best.

**Comment by davidgs** [comment]
Turns out that, I believe, it's because you rely on React 16, so any attempt to use React 18 (or even Node >16.x) fails. 

Might be time to update the libraries and dependencies. :-)

**Comment by hideokamoto-stripe** [comment]
Hello @davidgs ,
I update the React example to replace from CRA to Vite.
#956

Could you try to create a new one from Stripe CLI (`stripe samples create subscription-use-cases`) ?
Thanks.

**Comment by davidgs** [comment]
Vite? So an entirely different build system? I'm a little lost as to how that's going to help rather than just updating the requirements to more modern versions of Node and React?

**Comment by hideokamoto-stripe** [comment]
We migrated this example code to Vite for resolving this error:
https://github.com/stripe-samples/subscription-use-cases/issues/730#issuecomment-1890778148

Now we're continuing to work to upgrade each package.

**Comment by davidgs** [comment]
Interesting that I have never encountered this issue with any other CRA application. I've never had to resort to Vite.
